#!/bin/sh
masterlayout.sh &
bspc config external_rules_command external_rules.sh
bspc config removal_adjustment false

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 4
bspc config split_ratio 0.60
bspc config window_gap 12
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled

kill -9 $(pidof sxhkd)
sxhkd &
$HOME/.config/polybar/launch.sh
