#!/bin/sh
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 4
bspc config split_ratio 0.60
bspc config window_gap 12
bspc rule -a '*' state=tiled

BSPWMDIR="$HOME/.config/bspwm"
$BSPWMDIR/masterlayout.sh &
bspc config external_rules_command $BSPWMDIR/external_rules.sh
bspc config removal_adjustment false

kill -9 $(pidof sxhkd)
sxhkd &
$HOME/.config/polybar/launch.sh
