#!/bin/bash
state_new=$1
state_old=$(bspc query -T -d| grep "\*"| tail -1| rev| cut -c 9| rev)
#-=tiled; f=floating; F=fullscreen
if [[ $state_old == $state_new ]]; then
#echo "echo old == new => back to tiled"
	bspc node -t tiled
else
	case $state_new in
		"F")
			#echo "want a fullscreen window"
			bspc node -t fullscreen
			;;
		"f")
			#echo "want a floating window"
			bspc node -t floating
			;;
		*)
			#echo "setting window tiled"
			bspc node -t tiled
			;;
		esac
fi
